### ISSUE TITLE
Feature Request Summary

### ISSUE THREAD

**Issue by jlag34** [tremckinley/jammming3#3]
### Criteria 1: Objective Section  
* _Score Level: 4/4
* _Comment(s): Nice job choosing a feature that is a great improvement to the app and also challenging.
 
### Criteria 2: Background Section
* _Score Level: 4/4
* _Comment(s): Nice job talking about the problem Jammming has and how you're going to solve it.
 
### Criteria 3: Technical Design Section
* _Score Level: 4/4
* _Comment(s): You did a good job generalizing how to complete this really big task. It will definitely be a lot of work to get it finished.

### Criteria 4: Caveats Section
* _Score Level: 4/4
* _Comment(s): You're right. Getting the info once and saving it in state would definitely be better so that you don't have to continuously make the same call to the API. `componentWillMount` is being phased out by React so you will have to use `componentDidMount` which is fine. Just have a loading screen until the user's information is received.

### Overall Score: 16/16

You did a good job with your project. I like your idea in creating a way for users to see who is signed into Jammming. You did a good job generalizing how to complete it. I like that you thought deeply into your idea and came up with some good caveats. Remember not to use `componentWillMount` has it is being deprecated by React. Excellent job and keep up the good work!

**Comment by tremckinley** [comment]
Thank you for the feedback. This project, even without the code editing put my understanding to the test. I appreciated the challenge!
